paths:
    /product/:
      post:
        tags:
          - product
        description: add product
        produces:
          - application/json
        parameters:
          - in: body
            name: addProduct
            description: add product object
            required: true
            schema:
              $ref: "#/definitions/addProduct"
        responses:
          200:
            description: product added successfully...
          400:
            description: Bad request
          500:
            description: Server Error
      get:
        tags:
          - product
        description: retrieves all products
        produces:
          - application/json
        security:
          - bearerAuth: []
        responses:
          200:
            description: successful...
          400:
            description: Bad request
          500:
            description: Server Error

    
    /product/:name:
      get:
        tags:
          - product
        description: search product by name
        produces:
          - application/json
        parameters:
          - in: params
            name: searchProduct
            description: search product object
            required: true
            schema:
              $ref: "#/definitions/searchProduct"
        security:
          - bearerAuth: []
        responses:
          200:
            description: successful...
          400:
            description: Bad request
          500:
            description: Server Error
    /product/:productId:
      put:
        tags:
          - product
        description: update product details
        produces:
          - application/json
        security:
          - bearerAuth: []
        parameters:
          - in: body
            name: updatePrice
            description: update price object
            required: true
            schema:
              $ref: "#/definitions/updatePrice"
        responses:
          200:
            description: successfully updated
          400:
            description: Bad request
          500:
            description: Server Error
      delete:
        tags:
          - product
        description: deletes a particular product
        produces:
          - application/json
        security:
          - bearerAuth: []
        parameters:
          - in: params
            name: deleteProduct
            description: delete product object
            required: true
            schema:
              $ref: "#/definitions/deleteProduct"
        responses:
          200:
            description: successfully deleted...
          400:
            description: Bad request
          500:
            description: Server Error
definitions: # Schema defination for request body
  addProduct:
    properties:
      name:
        type: string
        required: true
      price:
        type: number
        required: true
      description:
        type: string
        required: true
  searchProduct:
    properties:
      name:
        type: string
        required: true
  updateProduct:
    properties:
      productId:
        type: string
        required: true
      price:
        type: number
        required: true
